image: node:latest

build:
  script:
    - node -v
    - npm -v
    - php -v
  #  - cd app/src/api
  #  - composer install
  #  - cd ../..
  #  - npm install
  #  - npm run build
  artifacts:
    paths:
    - app/dist
    expire_in: 1 week